apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reportflow-app
  annotations:
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Nestor10/reportflow
    targetRevision: main
    path: GitOpts/environments/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - PrunePropagationPolicy=Foreground
      - PruneLast=true
